I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 200, in script
    with longflash
  File "game/script.rpy", line 200, in <module>
    with longflash
NameError: name 'longflash' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 200, in script
    with longflash
  File "C:\Users\Anthony G\Downloads\Games\Renpy\renpy-7.3.2-sdk\renpy\ast.py", line 1380, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Anthony G\Downloads\Games\Renpy\renpy-7.3.2-sdk\renpy\python.py", line 2035, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Anthony G\Downloads\Games\Renpy\renpy-7.3.2-sdk\renpy\python.py", line 2028, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 200, in <module>
    with longflash
NameError: name 'longflash' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.2.320
TEST 1.0
Mon Jul 08 21:46:20 2019
